environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  github_oauth_token:
    secure: H1vW5fnfAOt5/c5f1qnaatUjFVAPc2oZnxDBFutJZL58LxAyJNRLtfIBrcHnSg8y  

version: 1.0.{build}
image: Visual Studio 2017
configuration: Debug

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  # version: '%GitVersion_FullSemVer%'
  version: '%GitVersion_NuGetVersion%'
  # package_version: '%GitVersion_LegacySemVerPadded%'
  package_version: '%GitVersion_NuGetVersion%'
  informational_version: '%GitVersion_InformationalVersion%'

install:
- choco install gitversion.portable -pre -y
- choco install opencover.portable -y
  #
  # install latest codecov (choco is behind of nuget)
- nuget install Codecov -OutputDirectory C:\NuGetTools\
- echo APPVEYOR_REPO_BRANCH  %APPVEYOR_REPO_BRANCH%
- echo APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH %APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH%
- IF "%APPVEYOR_PULL_REQUEST_NUMBER%"="" ( C:\ProgramData\chocolatey\lib\gitversion.portable\tools\gitversion.exe /l console /output buildserver /b %APPVEYOR_REPO_BRANCH% /c %APPVEYOR_REPO_COMMIT% ) ELSE ( C:\ProgramData\chocolatey\lib\gitversion.portable\tools\gitversion.exe /l console /output buildserver /c %APPVEYOR_REPO_COMMIT%)

- C:\ProgramData\chocolatey\lib\gitversion.portable\tools\gitversion.exe /l console /output buildserver /b %APPVEYOR_REPO_BRANCH% /c %APPVEYOR_REPO_COMMIT%
- git submodule update --init --recursive

before_build:
- dotnet restore ImageHash.sln

build_script:
- dotnet build ImageHash.sln

test_script:
- ps: .scripts\TestCoverage.ps1

after_test:
- ps: .scripts\pack.ps1
- ps: .scripts\Codecov.ps1

artifacts:
  - path: '**\*.nupkg'
    name: NuGet Packages

deploy:
  - provider: NuGet
    name: pre-release
    server: https://www.myget.org/F/coenm/api/v2/package
    api_key:
        secure: t8JtzPkpHidqOii+bLuSiOKgqzsdoSCBI3Sc/Uy6D9jWfxNd7zUUhhTgGHj5rpV9
    skip_symbols: true
    # symbol_server: https://www.myget.org/F/coenm/symbols/api/v2/package
    artifact: /.*\.nupkg/
    on:
        branch: /(master|release.*|develop)/	
